### ISSUE TITLE
Include the CloudFront URL for Application in the Administrator Welcome Email

### ISSUE THREAD

**Issue by jasonoma-aws** [aws-solutions/content-localization-on-aws#274]
**Is your feature request related to a problem? Please describe.**
Currently when users deploy the solution, the administrator is emailed a temporary password. This does not include the CloudFront URL to access the application.

![ContentLocalization](https://user-images.githubusercontent.com/95241370/146426452-ff90d7f0-6c97-411d-8adb-a8a61ef7cb15.jpg)

To access the application, the user needs to navigate to the CloudFormation deployment stack and access the value from the outputs of the "WebStack." Though this is a not an advanced task, it adds complexity especially for users that have not used or navigated CloudFormation before.

**Describe the feature you'd like**

Include the output URL form the WebStack inside the Administrator email or as a separate email depending on complexity which would remove a second searching step needed in the web console. 

**Additional context**

_Example email body: 

Your username is user@email.com and temporary password is *******

AWS CloudFormation stack:
https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2/********

Web Application URL: https://cloudfront.net/***********_

**Comment by ianwow** [comment]
The auth stack depends on the web stack for the user pool. But the auth stack's user pool resource sends the email. But the web stack creates the cloudfront resource. That circular dependency between user pool and cloudfront URL prevents us from including the URL in the invitation email.

In order to include the URL in the invitation email, I propose creating a new cloudformation resource that gets the temporary credentials from the auth stack and the URL from the web stack, then sends an email to the user-specified AdminEmail.

**Comment by jasonoma-aws** [comment]
This sounds like a solid approach to me.
