### ISSUE TITLE
Customization Inquiry

### ISSUE THREAD

**Issue by MohAlbakerKaw** [aws-solutions/content-localization-on-aws#364]
I would like to inquire about the possibility of customizing the solution to meet specific requirements.
Specifically, I would like to to remove all the features related to vision Analysis from the solution (optimizing the MIE cdk) for a faster and more cost-efficient version. I would appreciate it if you could provide guidance on the way to customize the solution to meet my specific requirements. 

Thank you for your time and assistance in this matter.

**Comment by julianklotz** [comment]
Hi @MohAlbakerKaw,

there are two options:

1. Customize the solution template – you can modify the template as needed and provide your own when setting up the solution
2. Talk to an AWS solutions expert or a frontend developer about it. It shouldn’t be hard to customize in your case, because you only want to *remove* a few bits

**Comment by MohAlbakerKaw** [comment]
yes, i'm working on the templates directly.
thank you
